rules:
  # SQL‐injection checks in C#
  - id: p/ci/csharp.lang.security.injection.sql-injection

  # XSS checks in C#
  - id: p/ci/csharp.lang.security.injection.xss

  # Insecure deserialization
  - id: p/ci/csharp.lang.security.injection.insecure-deserialization
