rules:
  # Detect SQL‐injection sinks in C#
  - id: p/ci/csharp.lang.security.injection.sql-injection

  # Detect XSS injection sinks in C#
  - id: p/ci/csharp.lang.security.injection.xss

  # Detect insecure deserialization in C#
  - id: p/ci/csharp.lang.security.injection.insecure-deserialization
