name: "DAST: Newman + ZAP Proxy 2"

on:
  workflow_dispatch:

jobs:
  dast-proxy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repo (code, postman/, zap-scripts/)
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Create a host folder for ZAP’s reports
      - name: Prepare report directory
        run: mkdir -p zap-reports

      # 3) Pull the official ZAP stable image
      - name: Pull OWASP ZAP image
        run: docker pull zaproxy/zap-stable:latest

      # 4) Start ZAP daemon, mounting your script + reports dir
      - name: Start ZAP daemon
        run: |
          docker run -d --name zap \
            -p 8080:8080 \
            -v $PWD/zap-scripts:/zap/scripts:ro \
            -v $PWD/zap-reports:/zap/wrk \
            zaproxy/zap-stable:latest \
            zap.sh -daemon -host 0.0.0.0 -port 8080 \
                   -config api.disablekey=true

      # 5) Wait until ZAP’s API is available
      - name: Wait for ZAP
        run: |
          for i in {1..12}; do
            curl --fail http://localhost:8080 && break
            sleep 5
          done

      # 6) Install Node.js & Newman
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman

      # 7) Replay your signed Postman collection through ZAP
      - name: Run Postman via ZAP proxy
        env:
          HTTP_PROXY: http://127.0.0.1:8080
          HTTPS_PROXY: http://127.0.0.1:8080
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
        run: |
          newman run postman/WaffarXPartnerApi.postman_collection.json \
            --globals postman/workspace.postman_globals.json

      # 8) Perform a full active scan (writes zap-active-report.html into /zap/wrk)
      - name: Run ZAP active scan
        run: |
          ZAP_CID=$(docker ps --filter name=zap -q)
          docker exec $ZAP_CID zap-full-scan.py \
            -t https://partners.waffarx.com \
            -r zap-active-report.html

      # 9) Stop ZAP
      - name: Stop ZAP
        run: docker stop zap

      # 🔟 Upload the HTML report from your host zap-reports folder
      - name: Upload ZAP Active Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-active-report
          path: zap-reports/zap-active-report.html
