name: "DAST: Newman + ZAP Proxy 21"

on:
  workflow_dispatch:

jobs:
  dast-proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull ZAP Docker image
        run: |
          docker pull zaproxy/zap-stable:latest
          echo "ZAP Docker image pulled successfully"

      - name: Start ZAP daemon in Docker
        run: |
          mkdir -p zap-reports
          docker run -d --name zap \
            -p 8080:8080 \
            -v "${{ github.workspace }}/postman/add-signature.js:/zap/scripts/add-signature.js:ro" \
            -v "${{ github.workspace }}/zap-reports:/zap/wrk" \
            --memory="2g" \
            zaproxy/zap-stable:latest \
            zap.sh -daemon -host 0.0.0.0 -port 8080 \
                   -config api.disablekey=true \
                   -config connection.timeoutInSecs=120 \
                   -config scanner.threadPerHost=10 \
                   -script /zap/scripts/add-signature.js
          echo "ZAP container started successfully"

      - name: Wait for ZAP to be ready
        run: |
          for i in {1..24}; do
            if curl --silent --fail http://127.0.0.1:8080; then
              echo "ZAP is ready"
              break
            fi
            echo "Waiting for ZAP to start (attempt $i/24)..."
            sleep 5
          done

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: |
          npm install -g newman
          echo "Newman installed successfully"

      - name: Run Postman collection via ZAP proxy
        env:
          HTTP_PROXY: http://127.0.0.1:8080
          HTTPS_PROXY: http://127.0.0.1:8080
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
        run: |
          newman run postman/WaffarXPartnerApi.postman_collection.json \
            --globals postman/workspace.postman_globals.json
          echo "Postman collection executed successfully"

      - name: Prepare ZAP for scan
        run: |
          echo "Preparing ZAP for scan..."
          
          # Install required tools with detailed logging
          docker exec -u root zap sh -c "apt-get update" || echo "apt-get update failed"
          docker exec -u root zap sh -c "apt-get install -y curl jq" || echo "Package installation failed"
          
          # Verify tools installation
          docker exec zap curl --version || echo "curl not installed"
          docker exec zap jq --version || echo "jq not installed"
          
          # Increase ZAP timeout settings
          docker exec zap curl -s "http://localhost:8080/JSON/core/action/setOptionTimeoutInSecs/?apikey=&Integer=120" \
            && echo "Timeout set to 120 seconds" \
            || echo "Failed to set timeout"
          
          docker exec zap curl -s "http://localhost:8080/JSON/ascan/action/setOptionScanTimeoutInMins/?apikey=&Integer=50" \
            && echo "Scan timeout set to 50 minutes" \
            || echo "Failed to set scan timeout"
          
          echo "ZAP preparation completed"

      - name: Run ZAP active scan via API
        run: |
          echo "Starting active scan..."
          
          # Start active scan with detailed output
          scan_start=$(docker exec zap sh -c 'curl -s "http://localhost:8080/JSON/ascan/action/scan/?apikey=&url=https://partners.waffarx.com&recurse=true"')
          echo "Scan start response: $scan_start"
          
          # Monitor scan progress
          start_time=$(date +%s)
          timeout=$((60 * 50))  # 50 minutes timeout
          last_status=0
          
          while true; do
            # Check total elapsed time
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
            
            if [ $elapsed -ge $timeout ]; then
              echo "Scan timed out after 50 minutes"
              break
            fi
            
            # Get scan status with error handling
            status_output=$(docker exec zap sh -c 'curl -s "http://localhost:8080/JSON/ascan/view/status/?apikey="')
            status=$(echo "$status_output" | jq -r '.status' 2>/dev/null || echo "error")
            
            if [[ "$status" == "100" ]]; then
              echo "Scan completed successfully"
              break
            elif [[ "$status" == "error" ]]; then
              echo "Error retrieving scan status: $status_output"
              sleep 10
              continue
            fi
            
            # Only log when status changes
            if [ "$status" != "$last_status" ]; then
              echo "Scan progress: $status%"
              last_status=$status
            fi
            
            sleep 30
          done
          
          # Generate HTML report
          echo "Generating scan report..."
          report_output=$(docker exec zap sh -c 'curl -s "http://localhost:8080/OTHER/core/other/htmlreport/?apikey=" -o /zap/wrk/zap-active-report.html 2>&1')
          echo "Report generation: $report_output"
          docker exec zap ls -l /zap/wrk || echo "Report directory not found"

      - name: Stop ZAP
        if: always()
        run: |
          if docker container inspect zap > /dev/null 2>&1; then
            docker stop zap || echo "Failed to stop ZAP container"
            echo "ZAP stopped successfully"
          else
            echo "ZAP container does not exist, skipping stop."
          fi

      - name: Upload ZAP Active Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-active-report
          path: zap-reports/zap-active-report.html

      - name: Capture ZAP logs
        if: always()
        run: |
          if docker container inspect zap > /dev/null 2>&1; then
            docker logs zap > zap-logs.txt 2>&1 || echo "Failed to capture ZAP logs"
          else
            echo "ZAP container not available for logs"
          fi