name: "DAST: Newman + ZAP Proxy 8"

on:
  workflow_dispatch:

jobs:
  dast-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code, Postman and script
        uses: actions/checkout@v3

      - name: Pull OWASP ZAP Docker image
        run: docker pull owasp/zap2docker-stable

      - name: Start ZAP daemon in Docker
        run: |
          mkdir -p zap-reports
          docker run -d --name zap \
            -p 8080:8080 \
            -v "${{ github.workspace }}/postman/add-signature.js:/zap/scripts/add-signature.js:ro" \
            owasp/zap2docker-stable \
            zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -script /zap/scripts/add-signature.js

      - name: Wait for ZAP to be ready
        run: |
          for i in {1..24}; do
            curl --silent --fail http://127.0.0.1:8080 || sleep 5 && continue
            echo "ZAP is up!"
            break
          done

      - name: Install Node.js & Newman
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g newman

      - name: Run Postman collection via ZAP proxy
        run: |
          newman run postman/WaffarXPartnerApi.postman_collection.json \
            --globals postman/workspace.postman_globals.json \
            --proxy http://127.0.0.1:8080

      - name: Run ZAP full active scan
        run: |
          # find the container ID (should be "zap")
          ZAP_CID=$(docker ps --filter "name=zap" -q)
          # health-check again inside container 
          for i in {1..12}; do
            docker exec $ZAP_CID curl --fail http://localhost:8080 || sleep 5 && continue
            break
          done
          docker exec $ZAP_CID zap-full-scan.py \
            -t https://partners.waffarx.com \
            -z "-config api.disablekey=true" \
            -d \
            -m 5 \
            -r /zap/wrk/zap-reports/zap-active-report.html

      - name: Stop ZAP
        if: always()
        run: docker stop zap

      - name: Upload ZAP HTML report
        uses: actions/upload-artifact@v4
        with:
          name: zap-active-report
          path: zap-reports/zap-active-report.html
