name: "DAST: Newman + ZAP Proxy"

on:
  workflow_dispatch:

jobs:
  dast-proxy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code, Postman files, and ZAP script
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Pull the official ZAP stable image
      - name: Pull OWASP ZAP image
        run: docker pull zaproxy/zap-stable:latest

      # 3) Start ZAP in the background with your signature script mounted
      - name: Start ZAP daemon
        run: |
          docker run -d --name zap \
            -p 8080:8080 \
            -v $PWD/zap-scripts:/zap/scripts:ro \
            zaproxy/zap-stable:latest \
            zap.sh -daemon -host 0.0.0.0 -port 8080 \
                   -config api.disablekey=true

      # 4) Wait until ZAP’s API is responding
      - name: Wait for ZAP
        run: |
          for i in {1..12}; do
            curl --fail http://localhost:8080 && break
            sleep 5
          done

      # 5) Install Node.js & Newman
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman

      # 6) Replay your Postman collection through ZAP proxy (skip TLS validation)
      - name: Run Postman via ZAP proxy
        env:
          HTTP_PROXY: http://127.0.0.1:8080
          HTTPS_PROXY: http://127.0.0.1:8080
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
        run: |
          newman run postman/WaffarXPartnerApi.postman_collection.json \
            --globals postman/workspace.postman_globals.json

      # 7) Perform a full active scan in the same ZAP container
      - name: Run ZAP active scan
        run: |
          ZAP_CID=$(docker ps --filter name=zap -q)
          docker exec $ZAP_CID zap-full-scan.py \
            -t https://partners.waffarx.com \
            -z "script=add-signature;type=httpsender;engine=ECMAScript;file=/zap/scripts/add-signature.js" \
            -r zap-active-report.html

      # 8) Tear down the ZAP container
      - name: Stop ZAP
        run: docker stop zap

      # 9) Upload the resulting HTML report
      - name: Upload ZAP Active Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-active-report
          path: zap-active-report.html
