name: "DAST: Newman + ZAP Proxy 6"
on:
  workflow_dispatch:

jobs:
  dast-proxy:
    runs-on: ubuntu-latest

    services:
      zap:
        image: owasp/zap2docker-stable
        ports: ["8080:8080"]
        options: >-
          --health-cmd='curl -s http://localhost:8080 || exit 1'
          --health-interval=10s
          --health-retries=12
        volumes:
          - ./postman/add-signature.js:/zap/scripts/add-signature.js
        command: >
          zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true
          -script /zap/scripts/add-signature.js

    steps:
      - name: Prepare report directory
        run: mkdir -p zap-reports

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for ZAP to start
        run: |
          for i in {1..24}; do
            curl --silent --fail http://127.0.0.1:8080 && break
            sleep 5
          done

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman via ZAP proxy
        run: |
          newman run postman/WaffarXPartnerApi.postman_collection.json \
            --globals postman/workspace.postman_globals.json \
            --proxy http://127.0.0.1:8080

      - name: Run ZAP active scan
        run: |
          ZAP_CID=$(docker ps --filter "ancestor=owasp/zap2docker-stable" -q)
          for i in {1..12}; do
            docker exec $ZAP_CID curl --fail http://localhost:8080 && break
            sleep 5
          done
          docker exec $ZAP_CID zap-full-scan.py \
            -t https://partners.waffarx.com \
            -z "-config api.disablekey=true" \
            -d \
            -m 5 \
            -r /zap/wrk/zap-reports/zap-active-report.html

      - name: Stop ZAP
        run: docker stop $ZAP_CID

      - name: Upload ZAP HTML report
        uses: actions/upload-artifact@v4
        with:
          name: zap-active-report
          path: zap-reports/zap-active-report.html
