# .github/workflows/dast-newman-zap.yml
name: "DAST: Newman + ZAP Proxy"

on:
  workflow_dispatch:

jobs:
  dast-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull OWASP ZAP Docker image
        run: docker pull zaproxy/zap2docker-stable:2.14.0

      - name: Start ZAP daemon
        run: |
          docker run -d --name zap \
            -p 8080:8080 \
            -v $PWD/zap-scripts:/zap/scripts:ro \
            zaproxy/zap2docker-stable:2.14.0 \
            zap.sh -daemon -host 0.0.0.0 -port 8080 \
                   -config api.disablekey=true

      - name: Wait for ZAP to start
        run: |
          for i in {1..10}; do
            curl --fail http://localhost:8080 || sleep 3
          done

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection via ZAP proxy
        run: |
          newman run postman/WaffarXPartnerApi.postman_collection.json \
            --globals postman/workspace.postman_globals.json \
            --proxy http://127.0.0.1:8080

      - name: Run ZAP active scan
        run: |
          ZAP_CID=$(docker ps --filter ancestor=zaproxy/zap2docker-stable:2.14.0 -q)
          docker exec $ZAP_CID zap-full-scan.py \
            -t https://partners.waffarx.com \
            -z "script=add-signature;type=httpsender;engine=ECMAScript;file=/zap/scripts/add-signature.js" \
            -r zap-active-report.html

      - name: Stop ZAP
        run: docker stop zap

      - name: Upload ZAP Active Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-active-report
          path: zap-active-report.html
