name: "DAST: Newman + ZAP Proxy 25"

on:
  workflow_dispatch:

jobs:
  dast-proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull ZAP Docker image
        run: docker pull zaproxy/zap-stable:latest

      - name: Start ZAP daemon in Docker
        run: |
          mkdir -p zap-reports
          chmod 777 zap-reports
          docker run -d \
            --name zap \
            -p 8080:8080 \
            -v "${{ github.workspace }}/postman/add-signature.js:/zap/scripts/add-signature.js:ro" \
            -v "${{ github.workspace }}/zap-reports:/zap/wrk" \
            --memory="2g" \
            --user root \
            zaproxy/zap-stable:latest \
            zap.sh -daemon -host 0.0.0.0 -port 8080 \
                   -config api.disablekey=true \
                   -config connection.timeoutInSecs=120 \
                   -config scanner.threadPerHost=10 \
                   -script /zap/scripts/add-signature.js

      - name: Wait for ZAP to be ready
        run: |
          for i in {1..24}; do
            if curl --silent --fail http://127.0.0.1:8080; then
              echo "ZAP is ready"
              break
            fi
            echo "Waiting for ZAP to start (attempt $i/24)..."
            sleep 5
          done

      # ... rest of the steps remain the same as previous version ...