name: "Semgrep SAST"

on:
  push:
    branches: [ main ]          # or 'master'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep static analysis
        run: |
          semgrep \
            --config .semgrep.yml \
            --sarif semgrep-report.sarif \
            --report semgrep-report.html \
            .

      - name: Upload Semgrep SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-report.sarif

      - name: Publish HTML report artifact
        uses: actions/upload-artifact@v4    # ← updated to v4
        with:
          name: semgrep-html-report
          path: semgrep-report.html
