name: SAST with Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep scan
      run: |
        semgrep --config .semgrep.yml \
                --report semgrep-report.html \
                --sarif semgrep-report.sarif .

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-html
        path: semgrep-report.html

    - name: Upload SARIF for GitHub security UI
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep-report.sarif
